spring.application.name=DunyaUlkeleri

# ===============================
# 1. SQLITE VERİTABANI BAĞLANTISI
# ===============================
# ===============================
# 1. POSTGRESQL VERİTABANI BAĞLANTISI
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/dunya_ulkeleri
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ayarları (Tabloları otomatik oluşturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# ===============================
# 2. HIBERNATE VE TABLO AYARLARI
# ===============================
# Java sınıflarına göre tabloları otomatik oluşturur ve günceller
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.open_in_view=false

# Arka planda çalışan SQL komutlarını konsolda gösterir (Hata bulmayı kolaylaştırır)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 3. BAŞLANGIÇ VERİSİ (data.sql) AYARLARI
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Güvenlik Ayarı
# Buradaki uzun karmaşık yazı senin gizli anahtarın. Gerçekte bunu dışarıdan (Environment Variable) vereceğiz.
jwt.secret=${JWT_SECRET}

# ===============================
# 4. E-POSTA (SMTP) AYARLARI
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true