part of '../country_detail_screen.dart';

extension _CountryDetailScreenIsoCodeImpl on CountryDetailScreenState {
  String? _getIsoCodeImpl(String country) {
    const Map<String, String> isoMap = {
      "Afganistan": "AF",
      "Almanya": "DE",
      "Amerika Birleşik Devletleri": "US",
      "Andorra": "AD",
      "Angola": "AO",
      "Antigua ve Barbuda": "AG",
      "Arjantin": "AR",
      "Arnavutluk": "AL",
      "Avustralya": "AU",
      "Avusturya": "AT",
      "Azerbaycan": "AZ",
      "Bahamalar": "BS",
      "Bahreyn": "BH",
      "Bangladeş": "BD",
      "Barbados": "BB",
      "Belçika": "BE",
      "Belize": "BZ",
      "Benin": "BJ",
      "Belarus (Beyaz Rusya)": "BY",
      "Bhutan": "BT",
      "Birleşik Arap Emirlikleri": "AE",
      "Birleşik Krallık": "GB",
      "Bolivya": "BO",
      "Bosna-Hersek": "BA",
      "Botsvana": "BW",
      "Brezilya": "BR",
      "Brunei": "BN",
      "Bulgaristan": "BG",
      "Burkina Faso": "BF",
      "Burundi": "BI",
      "Cezayir": "DZ",
      "Cibuti": "DJ",
      "Çad": "TD",
      "Çekya": "CZ",
      "Çin": "CN",
      "Danimarka": "DK",
      "Doğu Timor": "TL",
      "Dominik Cumhuriyeti": "DO",
      "Dominika": "DM",
      "Ekvador": "EC",
      "Ekvator Ginesi": "GQ",
      "El Salvador": "SV",
      "Endonezya": "ID",
      "Eritre": "ER",
      "Ermenistan": "AM",
      "Estonya": "EE",
      "Esvatini": "SZ",
      "Etiyopya": "ET",
      "Fas": "MA",
      "Fiji": "FJ",
      "Fildişi Sahili": "CI",
      "Filipinler": "PH",
      "Filistin": "PS",
      "Finlandiya": "FI",
      "Fransa": "FR",
      "Gabon": "GA",
      "Gambiya": "GM",
      "Gana": "GH",
      "Gine": "GN",
      "Gine-Bissau": "GW",
      "Grenada": "GD",
      "Guatemala": "GT",
      "Guyana": "GY",
      "Güney Afrika": "ZA",
      "Güney Kore": "KR",
      "Güney Sudan": "SS",
      "Gürcistan": "GE",
      "Haiti": "HT",
      "Hırvatistan": "HR",
      "Hindistan": "IN",
      "Hollanda": "NL",
      "Honduras": "HN",
      "Irak": "IQ",
      "İran": "IR",
      "İrlanda": "IE",
      "İspanya": "ES",
      "İsrail": "IL",
      "İsveç": "SE",
      "İsviçre": "CH",
      "İtalya": "IT",
      "İzlanda": "IS",
      "Jamaika": "JM",
      "Japonya": "JP",
      "Kamboçya": "KH",
      "Kamerun": "CM",
      "Kanada": "CA",
      "Karadağ": "ME",
      "Katar": "QA",
      "Kazakistan": "KZ",
      "Kenya": "KE",
      "Kıbrıs Cumhuriyeti": "CY",
      "Kırgızistan": "KG",
      "Kiribati": "KI",
      "Kolombiya": "CO",
      "Komorlar": "KM",
      "Kongo Cumhuriyeti": "CG",
      "Kongo Demokratik Cumhuriyeti": "CD",
      "Kosta Rika": "CR",
      "Kuveyt": "KW",
      "Kuzey Kore": "KP",
      "Kuzey Makedonya": "MK",
      "Küba": "CU",
      "Laos": "LA",
      "Lesotho": "LS",
      "Letonya": "LV",
      "Liberya": "LR",
      "Libya": "LY",
      "Liechtenstein": "LI",
      "Litvanya": "LT",
      "Lübnan": "LB",
      "Lüksemburg": "LU",
      "Macaristan": "HU",
      "Madagaskar": "MG",
      "Malavi": "MW",
      "Maldivler": "MV",
      "Malezya": "MY",
      "Mali": "ML",
      "Malta": "MT",
      "Marshall Adaları": "MH",
      "Mauritius": "MU",
      "Meksika": "MX",
      "Mısır": "EG",
      "Mikronezya": "FM",
      "Moğolistan": "MN",
      "Moldova": "MD",
      "Monako": "MC",
      "Moritanya": "MR",
      "Mozambik": "MZ",
      "Myanmar": "MM",
      "Namibya": "NA",
      "Nauru": "NR",
      "Nepal": "NP",
      "Nikaragua": "NI",
      "Nijer": "NE",
      "Nijerya": "NG",
      "Norveç": "NO",
      "Orta Afrika Cumhuriyeti": "CF",
      "Özbekistan": "UZ",
      "Pakistan": "PK",
      "Palau": "PW",
      "Panama": "PA",
      "Papua Yeni Gine": "PG",
      "Paraguay": "PY",
      "Peru": "PE",
      "Polonya": "PL",
      "Portekiz": "PT",
      "Romanya": "RO",
      "Ruanda": "RW",
      "Rusya": "RU",
      "Saint Kitts ve Nevis": "KN",
      "Saint Lucia": "LC",
      "Saint Vincent ve Grenadinler": "VC",
      "Samoa": "WS",
      "San Marino": "SM",
      "Sao Tome ve Principe": "ST",
      "Senegal": "SN",
      "Seyşeller": "SC",
      "Sırbistan": "RS",
      "Sierra Leone": "SL",
      "Singapur": "SG",
      "Slovakya": "SK",
      "Slovenya": "SI",
      "Solomon Adaları": "SB",
      "Somali": "SO",
      "Sri Lanka": "LK",
      "Sudan": "SD",
      "Surinam": "SR",
      "Suriye": "SY",
      "Suudi Arabistan": "SA",
      "Şili": "CL",
      "Tacikistan": "TJ",
      "Tanzanya": "TZ",
      "Tayland": "TH",
      "Togo": "TG",
      "Tonga": "TO",
      "Trinidad ve Tobago": "TT",
      "Tunus": "TN",
      "Tuvalu": "TV",
      "Türkiye": "TR",
      "Türkmenistan": "TM",
      "Uganda": "UG",
      "Ukrayna": "UA",
      "Umman": "OM",
      "Uruguay": "UY",
      "Ürdün": "JO",
      "Vanuatu": "VU",
      "Vatikan": "VA",
      "Venezuela": "VE",
      "Vietnam": "VN",
      "Yemen": "YE",
      "Yeni Zelanda": "NZ",
      "Yeşil Burun Adaları": "CV",
      "Yunanistan": "GR",
      "Zambiya": "ZM",
      "Zimbabve": "ZW",
    };
    return isoMap[country.trim()];
  }



}
